apiVersion: v1
kind: Secret
metadata:
  name: cte-aj
type: Opaque
data:
  # This is a base64 encoded registration token.  To generate:
  # echo <CM REGISTRATION TOKEN STRING> | base64 -w 0
  registration_token: TEJLUXk1Y21VTnBWS0tsMUxEQUtQN1FGMldGbkRLampEQlRWWnljZGN1NVpZejR4UzIwckRkNlRqV29RU09UOQo=

