apiVersion: v1
kind: Secret
metadata:
  name: cte-demo-token
  namespace: cte
type: Opaque
data:
  # This is a base64 encoded registration token.  To generate:
  # echo <CM REGISTRATION TOKEN STRING> | base64 -w 0
  registration_token: UXppdHViWGdrQUVvWEtGZ0VUcHdnS1VRWlZ5YU1TQnN6NTNacTJNd0Nid0FVOVQ1ZWhqZEJwZTYyVVlNd2Rnego=

