apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-test-pv
spec:
    capacity:
      storage: 1Gi
    storageClassName: nfs
    accessModes:
        -  ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - hard
        - nfsvers=4.1
    nfs:
        path: /data
        server: 192.168.2.73
