apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-test-claim
  namespace: cte
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

