apiVersion: v1
kind: Pod
metadata:
    name: cte-csi-demo
    namespace: VAR_NS
spec:
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: cte-claim
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
      - mountPath: "/mnt/azure"
        name: test-vol
    command:
     - "sleep"
     - "604800"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

