apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-test-claim
  namespace: VAR_NS
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cte-azurefile
  resources:
    requests:
      storage: 1Gi

