apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: VAR_NS
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi