apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-pv
    namespace: VAR_NS
spec:
    capacity:
      storage: 1Gi
    accessModes:
      -  ReadWriteMany
    storageClassName: standard
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - hard
    nfs:
        path: /data/cte
        server: VAR_NFS_SERVER_IP