apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-test-claim
spec:
  storageClassName: CM_STORAGE_CLASS
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

